services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 3s
      retries: 20

  app:
    build: .
    ports:
      - "8000:8000"
    user: "1000:1000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONITOR_PASSWORD: ${MONITOR_PASSWORD}
      TZ: Asia/Yerevan
    volumes:
      - .:/app
      - /mnt/work/it/TimeTracker/backups:/app/backups
      - "/mnt/work/_img_(orig_copy)/250:/app/static/img"
      - "/mnt/work/_img_(orig_copy)/250:/app/import_data"
      - "/mnt/work:/work"
      - "/mnt/work/Брендбук. Макеты. Рекламные шаблоны/260223 брендбук/site+:/app/static/logos"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
          
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
volumes:
  postgres_data: