"""initial schema

Revision ID: 20260930_0001
Revises: 
Create Date: 2026-10-01 00:03:57.288670
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260930_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('barcode_secret', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.Column('is_monitor', sa.Integer(), nullable=True),
    sa.Column('schedule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode_secret'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('ip_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mp_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('fandom', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allow_multiple', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tech_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_employee_id'), 'time_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_entries_id'), 'time_entries', ['id'], unique=False)
    op.create_table('day_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.Enum('WORK', 'OFF', 'VACATION', 'SICK', name='daytype'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uix_employee_date')
    )
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('deal_type_id', sa.Integer(), nullable=True),
    sa.Column('ip_id', sa.Integer(), nullable=True),
    sa.Column('mp_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deal_type_id'], ['deal_types.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_list.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mp_id'], ['mp_list.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_roles',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'role_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('reprimand', 'warning', 'commendation', 'performance_review', 'task_assignment', name='notificationtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'rejected', name='notificationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('tech_card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tech_card_id'], ['tech_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('task_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_type_id', 'tasks', ['task_type_id'], unique=False)
    op.create_table('deal_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_type_tasks',
    sa.Column('deal_type_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['deal_type_id'], ['deal_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_type_id', 'task_id')
    )
    op.create_index('idx_deal_type_tasks_deal_type_id', 'deal_type_tasks', ['deal_type_id'], unique=False)
    op.create_index('idx_deal_type_tasks_task_id', 'deal_type_tasks', ['task_id'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id')
    )
    op.create_table('independent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completion_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_independent_tasks_created_by_id'), 'independent_tasks', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_independent_tasks_status'), 'independent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_independent_tasks_task_id'), 'independent_tasks', ['task_id'], unique=False)
    op.create_table('role_tasks',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'task_id')
    )
    op.create_table('task_completion_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('defect_quantity', sa.Integer(), nullable=False),
    sa.Column('defect_comment', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'task_id', 'product_type_id', name='uq_deal_task_product')
    )
    op.create_index('idx_task_completion_data_deal_id', 'task_completion_data', ['deal_id'], unique=False)
    op.create_index('idx_task_completion_data_task_id', 'task_completion_data', ['task_id'], unique=False)
    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'on_break', 'completed', name='taskexecutionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('general_comment', sa.Text(), nullable=True),
    sa.Column('completion_percent', sa.Integer(), nullable=True),
    sa.CheckConstraint('completion_percent IS NULL OR completion_percent BETWEEN 0 AND 100', name='ck_task_execution_completion_percent'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', name='uq_notification_task')
    )
    op.create_index('idx_task_executions_employee_id', 'task_executions', ['employee_id'], unique=False)
    op.create_index('idx_task_executions_notification_id', 'task_executions', ['notification_id'], unique=False)
    op.create_table('task_product_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('points >= 0', name='task_product_points_points_check'),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'product_type_id', name='uq_task_product_points')
    )
    op.create_index('ix_task_product_points_product_type_id', 'task_product_points', ['product_type_id'], unique=False)
    op.create_index('ix_task_product_points_task_id', 'task_product_points', ['task_id'], unique=False)
    op.create_table('tech_card_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_card_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tech_card_id'], ['tech_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('independent_task_assignees',
    sa.Column('independent_task_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['independent_task_id'], ['independent_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('independent_task_id', 'employee_id'),
    sa.UniqueConstraint('notification_id')
    )
    op.create_index('ix_independent_task_assignees_employee_id', 'independent_task_assignees', ['employee_id'], unique=False)
    op.create_index('uq_independent_task_main_assignee', 'independent_task_assignees', ['independent_task_id'], unique=True, postgresql_where=sa.text('is_main'))
    op.create_table('task_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_execution_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_execution_id'], ['task_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_production_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_completion_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_completion_id'], ['task_completion_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_production_distribution_employee_id', 'task_production_distribution', ['employee_id'], unique=False)
    op.create_index('idx_task_production_distribution_task_completion_id', 'task_production_distribution', ['task_completion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_production_distribution_task_completion_id', table_name='task_production_distribution')
    op.drop_index('idx_task_production_distribution_employee_id', table_name='task_production_distribution')
    op.drop_table('task_production_distribution')
    op.drop_table('task_breaks')
    op.drop_index('uq_independent_task_main_assignee', table_name='independent_task_assignees', postgresql_where=sa.text('is_main'))
    op.drop_index('ix_independent_task_assignees_employee_id', table_name='independent_task_assignees')
    op.drop_table('independent_task_assignees')
    op.drop_table('tech_card_tasks')
    op.drop_index('ix_task_product_points_task_id', table_name='task_product_points')
    op.drop_index('ix_task_product_points_product_type_id', table_name='task_product_points')
    op.drop_table('task_product_points')
    op.drop_index('idx_task_executions_notification_id', table_name='task_executions')
    op.drop_index('idx_task_executions_employee_id', table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index('idx_task_completion_data_task_id', table_name='task_completion_data')
    op.drop_index('idx_task_completion_data_deal_id', table_name='task_completion_data')
    op.drop_table('task_completion_data')
    op.drop_table('role_tasks')
    op.drop_index(op.f('ix_independent_tasks_task_id'), table_name='independent_tasks')
    op.drop_index(op.f('ix_independent_tasks_status'), table_name='independent_tasks')
    op.drop_index(op.f('ix_independent_tasks_created_by_id'), table_name='independent_tasks')
    op.drop_table('independent_tasks')
    op.drop_table('explanations')
    op.drop_index('idx_deal_type_tasks_task_id', table_name='deal_type_tasks')
    op.drop_index('idx_deal_type_tasks_deal_type_id', table_name='deal_type_tasks')
    op.drop_table('deal_type_tasks')
    op.drop_table('deal_products')
    op.drop_index('idx_tasks_type_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('product_types')
    op.drop_table('notifications')
    op.drop_table('employee_roles')
    op.drop_table('deals')
    op.drop_table('day_status')
    op.drop_index(op.f('ix_time_entries_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_employee_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_table('tech_cards')
    op.drop_table('task_types')
    op.drop_table('system_settings')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('mp_list')
    op.drop_table('ip_list')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('deal_types')
    sa.Enum(
        'reprimand', 'warning', 'commendation', 'performance_review',
        'task_assignment', name='notificationtype'
    ).drop(op.get_bind(), checkfirst=True)
    sa.Enum('draft', 'sent', 'rejected', name='notificationstatus').drop(
        op.get_bind(), checkfirst=True
    )
    sa.Enum('WORK', 'OFF', 'VACATION', 'SICK', name='daytype').drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
